# Generated by Django 4.1.2 on 2022-10-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
